info:
  contact: {}
paths:
  /index:
    get:
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - 首页
  /user/createUser:
    get:
      parameters:
      - description: 用户名
        in: query
        name: name
        type: string
      - description: 密码
        in: query
        name: password
        type: string
      - description: 确认密码
        in: query
        name: repassword
        type: string
      responses:
        "200":
          description: 'code": "msg"}'
          schema:
            type: string
      summary: 创建用户
      tags:
      - 用户模块
  /user/deleteUser:
    delete:
      parameters:
      - description: 用户ID
        in: query
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: 'code": "msg"}'
          schema:
            type: string
      summary: 删除用户
      tags:
      - 用户模块
  /user/getUserList:
    get:
      responses:
        "200":
          description: 'code": "msg"}'
          schema:
            type: string
      summary: 获取用户列表
      tags:
      - 用户模块
  /user/login:
    post:
      parameters:
      - description: 用户名
        in: formData
        name: name
        required: true
        type: string
      - description: 密码
        in: formData
        name: password
        required: true
        type: string
      responses:
        "200":
          description: 'code": "msg"}'
          schema:
            type: string
      summary: 登录
      tags:
      - 用户模块
  /user/updateUser:
    post:
      parameters:
      - description: 用户ID
        in: query
        name: id
        required: true
        type: integer
      - description: 用户名
        in: formData
        name: name
        type: string
      - description: 密码
        in: formData
        name: password
        type: string
      - description: 邮箱
        in: formData
        name: email
        type: string
      - description: 手机号
        in: formData
        name: phone
        type: string
      - description: 确认密码
        in: formData
        name: repassword
        type: string
      responses:
        "200":
          description: 'code": "msg"}'
          schema:
            type: string
      summary: 更新用户
      tags:
      - 用户模块
swagger: "2.0"
